### ISSUE TITLE
Kobo Aura HD: Backlight does not get enabled

### ISSUE THREAD

**Issue by skinkie** [baskerville/plato#106]
I have just upgraded to the latest firmware of the Kobo Aura HD, and installed Plato for the first time. My compliments it looks great. What does not work for me is the backlight button. Neighter "the physical button" nor the on screen button.

**Comment by baskerville** [comment]
What's the outputs of `grep 'frontlight =' Settings.toml`?

Could you run the attached binary and try:
- Toggling the frontlight with the physical button (the frontlight icon should change).
- Tapping the frontlight icon (when it isn't disabled, otherwise it won't do anything).

Please post the resulting `info.log`.

[plato-0.8.5-test01.zip](https://github.com/baskerville/plato/files/4359027/plato-0.8.5-test01.zip)

**Comment by skinkie** [comment]
@baskerville I'll do so shortly after I have recovered the eReader. My current problem is that after upgrading I changed the "hide .kobo files", instead of doing this before the upgrade. Which resulted in a crashing koreader and plato. Plato reboots, koreader gives me a crashing screen.

https://github.com/koreader/koreader/issues/5983

**Comment by skinkie** [comment]
@baskerville Thanks for making the test version. After reinstalling the entire device, everything works as expected with the release version. I now see the nice slide, and the button on the top of the device also works.
