### ISSUE TITLE
Build error: linking with `arm-linux-gnueabihf-gcc` failed: exit code: 1

### ISSUE THREAD

**Issue by tatung** [baskerville/plato#14]
I was trying to first build plato on Ubuntu LTS 12.04 32-bit, then I got this error:

>  linking with `arm-linux-gnueabihf-gcc` failed: exit code: 1

I have already installed `gcc-4.6-arm-linux-gnueabihf`. What should I do now?

P.S. When follow your building document, I couldn't find the `config` file so I created one in `~/.cargo` and add the `linker `as well as `rustflag`. Might it be a problem?

**Comment by baskerville** [comment]
The documentation regarding the [build process](https://github.com/baskerville/plato/blob/master/doc/BUILD.md) is incomplete. It tells you how to compile a *Rust* program for your device, not how to build *Plato*.

The error probably comes from the fact that you haven't build the thirdparty dependencies. You'll need to do that (don't forget the *mupdf* wrapper in `src/wrapper`).

@traycold seems to be working on automating the build process in his [fork](https://github.com/traycold/plato).

**Comment by tatung** [comment]
I see. Thank you, I will try to build the thirdparty dependencies first.
So should the build process be like:
- Build all thirdparty dependencies
- Go to `src/wrapper` and build _mupdf_
- Go to `src` and run the cargo command
I will also try @traycold fork.

**Comment by baskerville** [comment]
The complete workflow is:

1. Build the thirdparty dependencies.
2. Build the *mupdf* wrapper in `./src/wrapper`.
3. Copy the libraries (`.so` files) generated in the previous steps to `./libs`.
4. Build *Plato* (in `.`).

**Comment by traycold** [comment]
hi,
it's true, I tried to do the build autonomously, but up to now I didn't succeed.

The first try I made is to do a complete build with dependencies:
- first, I made a script to download the dependencies tarball (problem: I don't know if there are version constraints; I take the latest version available at the moment)
- then do the build using the build-kobo.sh script present for each library to build (I needed some minor modification in the scripts in some cases, you can see them in git history)
- I stopped during the build of freetype, that I was not able to overcome (actually, reading some documentation on internet, I tried first the build of freetype without harfbuzz, than build harfbuzz, than rebuild freetype with harfbuzz: at this last stage I had an error - now I don't have the build env at hand and don't remember exactly the error message)

Then I tried a partial build, starting from the third-paty binaries provided in the latest release of plato:
- put the *.so.* files in the folder /lib of the plato root (stripping the part after ".so" in the filename)
- perform the rust build of plato
- even this try failed, at a certain point (I think almost at the end of the build process) the process failed with this error:
`error: linking with `arm-linux-gnueabihf-gcc` failed: exit code: 1
  |
  = note: "arm-linux-gnueabihf-gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-L" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato0-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato1-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato10-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato11-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato12-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato13-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato14-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato15-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato2-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato3-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato4-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato5-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato6-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato7-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato8-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.plato9-702e17353ddea7f9c67f72c79ad9adc.rs.rcgu.o" "-o" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/plato-9afef44f4b0815f8.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps" "-L" "/home/serdimic/Projects/private/plato/target/release/deps" "-L" "libs" "-L" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/build/backtrace-sys-6a4d7ac47e57b93e/out/.libs" "-L" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib" "-l" "djvulibre" "-l" "mupdf" "-l" "mupdfwrapper" "-l" "harfbuzz" "-l" "freetype" "-l" "jpeg" "-l" "png16" "-l" "openjp2" "-l" "jbig2dec" "-l" "bz2" "-l" "z" "-l" "m" "-Wl,-Bstatic" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libchrono-164e3bdfc8d87269.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libfnv-c660230963932ea1.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libisbn-97ccd2778fc5093c.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/liberror_chain-89730f7e2c3388fa.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libbacktrace-779dca65f1c33d38.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/librustc_demangle-b50f5399c7640b9e.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libcfg_if-116f35025e44a104.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libunicode_normalization-ab2d0f97ab907c78.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libnum-d84db56af439e8fe.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libglob-0420729b21f6a798.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libbacktrace_sys-eaae4df84c3dc48a.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libserde_json-d31edb0bb784c3d3.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libitoa-dd718dcb5909991a.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libserde-ad966d52b5c7c46c.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libdtoa-b9b8987ebf40cfa7.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libdowncast_rs-aeac3ff02cc5b283.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libtime-036ae783abfe939f.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libpng-f22d1e9c32e10eee.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libinflate-dd873de0911fc01c.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libnum_iter-bef47c252c62ace6.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libnum_integer-a345a6b2f978b312.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libnum_traits-c3f1d079b266d6dc.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libbitflags-2d49f462f4af4fae.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libdeflate-e9d465a9c35785ed.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libbyteorder-814875b7e48ef5ad.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libadler32-dc1686543a13ebac.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libtitlecase-11a637ec2b2d1682.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libregex-5e52672ed6666ed7.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libutf8_ranges-a8caf0cee9782644.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libregex_syntax-fbcf5ed96d40e8ef.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libucd_util-b3d29b92d27dc307.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libthread_local-84d1b971a746bf60.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/liblazy_static-bb48956922c9485a.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libunreachable-93c24943a6bd0ad3.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libvoid-d551335ad355efe1.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libaho_corasick-b4ad38f658810704.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/libmemchr-473a0c062eb2db4e.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/liblibc-8f1fb18b029c0d45.rlib" "/home/serdimic/Projects/private/plato/target/arm-unknown-linux-gnueabihf/release/deps/liblazy_static-9c5965d748c4b1b0.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libstd-6bb22b30207722f2.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libpanic_unwind-8d1c3982c0670998.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liballoc_jemalloc-2a12cd93029b9807.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libunwind-a5d3ff19e13d9f37.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liballoc_system-c5f69e7df1f06d84.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liblibc-e2e7ce88a6c41eea.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/liballoc-3d7473d271611dc2.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libstd_unicode-58e7a51af24928de.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcore-6806ae6018eec5e7.rlib" "/home/serdimic/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/arm-unknown-linux-gnueabihf/lib/libcompiler_builtins-85fd2d595ec0faf9.rlib" "-Wl,-Bdynamic" "-l" "util" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /home/serdimic/Projects/private/gcc-linaro-arm-linux-gnueabihf-4.8-2013.04-20130417_linux/bin/../lib/gcc/arm-linux-gnueabihf/4.8.1/../../../../arm-linux-gnueabihf/bin/ld: warning: libstdc++.so.6, needed by libs/libdjvulibre.so, not found (try using -rpath or -rpath-link)
          libs/libdjvulibre.so: undefined reference to `__cxa_free_exception@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__cxa_guard_acquire@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__cxa_end_catch@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `operator delete(void*)@GLIBCXX_3.4'
          libs/libdjvulibre.so: undefined reference to `vtable for __cxxabiv1::__si_class_type_info@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__cxa_begin_catch@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__gxx_personality_v0@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__aeabi_atexit@CXXABI_ARM_1.3.3'
          libs/libdjvulibre.so: undefined reference to `__cxa_allocate_exception@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `operator delete[](void*)@GLIBCXX_3.4'
          libs/libdjvulibre.so: undefined reference to `__cxa_guard_abort@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__cxa_rethrow@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `operator new(unsigned int)@GLIBCXX_3.4'
          libs/libdjvulibre.so: undefined reference to `std::set_new_handler(void (*)())@GLIBCXX_3.4'
          libs/libdjvulibre.so: undefined reference to `std::terminate()@GLIBCXX_3.4'
          libs/libdjvulibre.so: undefined reference to `vtable for __cxxabiv1::__vmi_class_type_info@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__cxa_pure_virtual@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `vtable for __cxxabiv1::__class_type_info@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__cxa_end_cleanup@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__cxa_throw@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `__cxa_guard_release@CXXABI_1.3'
          libs/libdjvulibre.so: undefined reference to `operator new[](unsigned int)@GLIBCXX_3.4'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `plato`.
` 
Maybe the error is explained by this remark in the build instructions:
>  In order to build for this OS / architecture you can, for example, install Ubuntu LTS 12.04 (the GLIBC version must be old enough) in a VM and install the following package: gcc-4.6-arm-linux-gnueabihf

I tried to build using as Host Fedora 27 x64, and using the Linaro toolchain [downloaded](https://github.com/kobolabs/Kobo-Reader/tree/master/toolchain) from kobo github repo

When I will have more time, I will try doing as suggested by @baskerville , i.e. creating a VM dedicated to the build.
