### ISSUE TITLE
[question] What are the differences (in rationale) between Koreader and Plato?

### ISSUE THREAD

**Issue by lpan** [baskerville/plato#144]
Hi Bastien,

Thanks so much for starting and maintaining this project!

I am wondering what are the major differences between Plato and Koreader. Specifically, why did you start this project given that koreader already exists? How is Plato significantly better than koreader?

Thanks again!
Lawrence

**Comment by welps** [comment]
I think you're likely to get a non-answer in that you should try both koreader and plato, and see which you like best. [1-click installs for each app exist on the mobileread forum if you're unaware](https://www.mobileread.com/forums/showthread.php?t=314220).

Both applications have their own +/-s when it comes to tinkering and rolling your own features if you're not satisfied with what's there. I know some people like that koreader uses lua because they don't have to compile to see changes. Personally I find plato more aesthetically pleasing and performant. There's a clearer separation of concerns with a [hooks](https://github.com/baskerville/plato/blob/master/doc/HOOKS.md) system that allows people to roll what they generally want (some mechanism to import/sync/refresh content) without adding onto the cruft of the main application.

**Comment by baskerville** [comment]
The three main readers have recently been [reviewed](https://www.reddit.com/r/kobo/comments/jatkxu/just_tested_plato_and_ko_reader_to_compare_to/).
