### ISSUE TITLE
Add Saved Searches

### ISSUE THREAD

**Issue by de3sw2aq1** [baskerville/plato#155]
It would be nice to have a way to save search queries.

The new [complex queries supported by search](https://github.com/baskerville/plato/blob/master/doc/MANUAL.md#search-bar) are really nice. I leave a lot of finished books on my device and would like to use `'!F` frequently. I'd like to use "not finished, sort by opened, reverse order" as my default view.

A neat idea might be to add the ability to change the sort order in the query. Then you could replace the sort order drop down with a list of saved searches (perhaps configured via `Settings.toml` which would be prepopulated with the current set of "sort by" options by default). Or maybe just a list of saved searches above the sort orders, and keep the existing sorting design as is.

**Comment by baskerville** [comment]
As mentioned in the manual, if you tap and hold a text input field you'll get a menu with all the previous inputs. However, the input history doesn't persist across restarts. I think it would be better, in order to achieve your goal, to introduce a secondary sort order, you'll then get the expected result with *sort by __progress__ and then by __date opened__*.

**Comment by de3sw2aq1** [comment]
Thanks, this new **status** sort order is exactly what I was trying to achieve.
