### ISSUE TITLE
Gradient rendering in Plato

### ISSUE THREAD

**Issue by skinkie** [baskerville/plato#196]
I just noticed while making the example below that the gradient on the first page looks poor in plato, when compared to the stock reader. When applied dithering #150 the example still gives a 'wave-pattern'.

[ext.zip](https://github.com/baskerville/plato/files/7111329/ext.zip)

**Comment by baskerville** [comment]
I didn't notice any problem on my *Glo HD*: the first page is equivalent to the `cover_image.jpg` file included in the EPUB. The JPEG itself exhibits some micro banding glitches, probably because of the compression algorithm. Can you provide a screenshot of how it renders on your device?

**Comment by skinkie** [comment]
I think it would be fair to say that the stock reader does a different kind of poor job.

Plato, almost impossible to see, but there are two patterns on the south side of the reader.
![IMG_20210908_114525](https://user-images.githubusercontent.com/502394/132487603-c9122679-abd3-495e-b48a-e7a012104985.jpg)

Stock, applies no dithering, just more bands than Plato without dithering.
![IMG_20210908_114642](https://user-images.githubusercontent.com/502394/132487774-de594bfc-9414-43a3-8847-1e79f89258dd.jpg)

I think this might be an edge case, so no prioritization required from my perspective.

**Comment by baskerville** [comment]
What's your device?

**Comment by skinkie** [comment]
Kobo Aura HD

**Comment by NiLuJe** [comment]
As @baskerville said, the source gradient is already fucked because JPG, so it's kinda hard to get it right either way ;).

You've mentioned trying to apply dithering, but failed to mention which kind ;).

FWIW, it looks as good as it can over here on a H2O (which is the closest device one can get to an Aura HD), given the state of the source and the fact that it's a gradient, when run through IM's ordered dither.

Here's what's actually drawn to the fb that way (speaking of, I wouldn't mind an fbgrab of what you think is going wrong, because it's kind of hard to tell in your pictures, besides the fact that it's horribly borked in Nickel ;)).

![plato_b196](https://user-images.githubusercontent.com/111974/132990895-04e14200-801c-4b55-a909-1a9cee6e1168.png)

**Comment by skinkie** [comment]
> You've mentioned trying to apply dithering, but failed to mention which kind ;).

The kind you can select in the menu ;)
