### ISSUE TITLE
Kobo Clara HD

### ISSUE THREAD

**Issue by woachk** [baskerville/plato#21]
The correct touch settings aren't currently there for the Clara HD.

**Comment by baskerville** [comment]
The *Clara HD* wasn't added to the list of devices yet. But I plan on releasing a new version this week with the appropriate changes.

**Comment by baskerville** [comment]
I've released [0.5.0](https://github.com/baskerville/plato/releases/tag/0.5.0).

**Comment by woachk** [comment]
@baskerville so the issue is that the power button doesn't work, so that I have to plug in the reader to the USB port to wake up the Kobo.

**Comment by baskerville** [comment]
So, if you're running *Plato* and you follow this procedure:

1. Put the device to sleep using the power button.
2. Wait at least one minute.
3. Press the power button.
 
Then the device doesn't wake up?

**Comment by woachk** [comment]
@baskerville so it works if you wait a minute but not if you do it directly unlike KOReader or the stock Nickel reader.

Thanks. :)

**Comment by woachk** [comment]
Also, Plato doesn't do panel refreshes. Is that safe behaviour?

**Comment by baskerville** [comment]
I'm assuming that you're referring to the full screen refreshes that occur every *n*-th page turn (or every chapter in the recent *Nickel* versions).

This can be controlled by the `refresh-every` setting in the *reader* section. However, I can understand that the current default might seem surprising to a newcomer. Within the reader, the screen can also be manually refreshed by holding a finger in the middle band.

The reason for doing this is to restore the clarity of the *white* background which gets dirty because of the *ghosting effect*: the black of the previous pages leaves a trace in the background.

Since *koreader* has no constraints on this, that probably means that there's no safety issues related to the high values.

**Comment by woachk** [comment]
@baskerville it's worth noting that KOReader & Nickel seem to do panel refreshes just before going on suspend when you click on the power button. :)

Thanks for your answers, and yeah the default was quite a bit surprising for me.

**Comment by 7596ff** [comment]
Is the Kobo Clara HD a supported device now? It is not reflected in the readme.

**Comment by baskerville** [comment]
I forgot to add it to the list: it should [work fine](https://www.mobileread.com/forums/showpost.php?p=3756781&postcount=202).
