### ISSUE TITLE
[Bug] Insane Battery Usage? Libra 2

### ISSUE THREAD

**Issue by seniorm0ment** [baskerville/plato#307]
Not sure if it is specifically Plato related, but it seemed to happen around the same time. 

Kobo Libra 2, the device can be around 96% charged. Then after about a day and a half of it being in sleep, using the sleep cover (shows Plato's sleeping menu when opening the cover and then switches to Plato) so it seems like it is sleeping.

But after about a day and a half of no usage just being in sleep, I turn the device on (open sleep lid) and it's already at 17%. From just being at 96% a day and a half ago.

**Comment by seniorm0ment** [comment]
Been playing around with it. It's really hard to tell if Plato is the exact cause, but it seems that way.
I exited Plato and left it on Kobo's main screen, and put it to sleep. I checked back 2 days later and it still had plenty of battery.

I did the same but launched Plato first, and then put it to sleep. 2 days later I check on it, and it is completely dead.
The backlight is not on when the cover is shut (I peeked). And it shows it's sleeping. So it seems to be working as intended, but it seems like maybe there is some CPU or Memory leak possibly that is killing the battery, despite being in "sleep" mode.

**Comment by baskerville** [comment]
Can you replace your *Plato* binary with the one attached in this comment and post the contents of *info.log* after having witnessed a battery drain?

[plato-0.9.38-log_events-01.zip](https://github.com/baskerville/plato/files/12269130/plato-0.9.38-log_events-01.zip)

**Comment by neabb** [comment]
I want to corroborate that I too experience massive battery drain when idle with sleepcover on my Libra 2 whilst Plato is running.
I installed Plato pretty much immediately after I purchased my Kobo - it is a lot better than stock!  But I noticed stock is able to operate for weeks - Plato seems to run down after a few days.

**Comment by neabb** [comment]
Want to follow up - either I have installed the file into "\.adds\plato\" and overwritten the binary, currently I can not get it to work as Plato gets stuck at launch and crashes back to Nickel.

**Comment by seniorm0ment** [comment]
Haven't had a chance to do the log events Plato, but if I can find some time I will.
I have done a reinstall of Plato though since this issue, and I didn't notice resolution. But curiously @neabb can you link the mobileread page you downloaded from?
Because I am using the one click install that has NickelMenu+Plato (no KOReader)

**Comment by neabb** [comment]
Hi @seniorm0ment 

I believe we are getting it from the same source.
Here is the link to the MobileRead forum topic:
https://www.mobileread.com/forums/showthread.php?t=314220
I just use the one called Plato but it shouldn't really matter which you choose after installing KFMon (I don't believe they interact with eachother at all).

![Kobo Plato One Click](https://github.com/baskerville/plato/assets/48165558/bfe6943e-6c5a-4d0a-b369-0a78880a2f51)

**Comment by neabb** [comment]
I haven't experienced any egregious battery drain since installing the events log binary (which I'm guessing is identical to the latest release.  In about 2 days, I have lost 9% battery without usage.  I'll keep you posted and submit the logs when something egregious happens.

**Comment by baskerville** [comment]
> the events log binary which I'm guessing is identical to the latest release

The only difference is that it writes every input event to standard error.

**Comment by neabb** [comment]
Touching base with a development.

Attached is the info file.

[info.log](https://github.com/baskerville/plato/files/12330560/info.log)

Last night I launched Plato on my Libra 2, shut the sleep cover on the main menu and left it over night on ~93%.  Ideally I wanted to leave it over the span of several nights but... when I opened the sleep cover this morning (~10 hours)... it was back on NickelMenu and with 10% battery drained.  I had noticed I had been seeing a lot more of Nickel recently... figured it was just because of the drain...

So not only is something seemingly intensive happening in the background draining the battery, something dubious is causing a crash... sounds like a mystery for the great Baskerville...

**Comment by NiLuJe** [comment]
@baskerville: Devices with physical keys have key repeat enabled, assuming you're not waking up yourself on those events, this *should* be pretty harmless and *not* prevent suspend (although, admittedly, it's been a while since I double-checked).
And since everything is terrible and sleep covers are implement as an EV_KEY and not an EV_SW, they *do* repeat, which is hilarious.

Because I neither actually trust that to hold true, and because it make logs a right old mess, we disable key repeat on suspend in KOReader (via EVIOCSREP).

(I don't recall if I ever checked what Nickel does, because it takes a patch to prevent it from grabbing event0, and I'm too lazy ;p).

**Comment by NiLuJe** [comment]
Well, that's... new ;D.

I've seen some janky logs from all kinds of wonky or chattering hall sensors, but that one is weird.

I... don't really see a sensible way of handling that that couldn't backfire in fun and interesting ways. (e.g., assuming the first REPEAT is a PRESS if a PRESS was never caught, but then you have to hope that you'll actually get a RELEASE at some point ;D).

**Comment by baskerville** [comment]
@neabb Could you, using the same binary, provide the log for the following sequence of actions :
- Put the device to sleep using the power button.
- Wait 30 seconds.
- Close the cover.
- Wait 5 seconds.
- Open the cover.

**Comment by neabb** [comment]
@baskerville 
[info.log](https://github.com/baskerville/plato/files/12340485/info.log)

**Comment by baskerville** [comment]
Please try the attached binary: the device should now sleep properly when the cover is closed.

[plato-0.9.38-cover_repeat-01.zip](https://github.com/baskerville/plato/files/12343735/plato-0.9.38-cover_repeat-01.zip)

**Comment by neabb** [comment]
Just wanted to report my usage with the latest binary 'plato-0.9.38-cover_repeat-01':

Last night battery status: 99%
This morning battery status: 99%
Tonight's battery status: 99%
Needless to say, I haven't done much reading...

Otherwise a tremendous success - Plato on Libra 2 with Sleep Cover is fixed!  No more massive drain.
Thank you very much for fixing that @baskerville

**Comment by seniorm0ment** [comment]
I assume this would apply in the next update if I just want to wait for it?
Then I can just update directly from my device instead of needing to connect to PC.

**Comment by seniorm0ment** [comment]
Just updated to the latest Plato release

It seems like battery life has improved, however still seems like a good bit of drain. I read for about 30min the other night on a full charge, put it to sleep, it's been 2 days sitting on the table idle sleeping, checked today and it has about a quarter of battery left.

**Comment by rafcon-dev** [comment]
> Just updated to the latest Plato release
> 
> It seems like battery life has improved, however still seems like a good bit of drain. I read for about 30min the other night on a full charge, put it to sleep, it's been 2 days sitting on the table idle sleeping, checked today and it has about a quarter of battery left.
> 
> Edit: It turned on for a min, now it seems like it's dead so maybe it was on the verge of dying. So yeah battery life still seems not amazing like it should be

Might want o try the latest version, some battery isues have been solved
