### ISSUE TITLE
Ability to adjust text contrast like in KOReader

### ISSUE THREAD

**Issue by verebes1** [baskerville/plato#37]
Please add the ability to adjust the text contrast like in KOReader. 
I really prefer Plato for its speediness and clear interface, however that feature is a much-needed one especially for pdf's which have a greyish font. 

Thank you in advance.
Great app

**Comment by baskerville** [comment]
Could you provide an example PDF?

**Comment by verebes1** [comment]
Here you go



David

**Comment by verebes1** [comment]
Let me know if you got the attachment via email. It went as maildrop

**Comment by baskerville** [comment]
I didn't receive the attachment.

**Comment by verebes1** [comment]
I have resent it to your email 

David Verbenyi

**Comment by verebes1** [comment]
Did you get it this time??

**Comment by baskerville** [comment]
Yes, I did.

**Comment by rien333** [comment]
Wouldn't it be somewhat simpler to provide just an option to maximize contrast (e.g. convert everything to black and white, or something in a dense to black and white range)? Or pre-process the "faulty" pdfs yourself? (tbh, I've never seen a pdf that is too gray, nor is there a (desktop) pdf reader I can think of  that provides contrast enhancement funtionality)

In the more general case, that's exactly what you want - to enhance the contrast to the best possible value. If this became a toggle/button instead of two sliders, then the interface for pdf viewing could be cleaned up a bit by moving it into the other row of buttons. Now, I'm constantly worrying whether my contrast is the best it could be + all the UI elements  of the overlay together take up half the screen!
