### ISSUE TITLE
MuPDF unbounded memory growth

### ISSUE THREAD

**Issue by bricewge** [baskerville/plato#55]
When reading a PDF, scanned pages of a book, I got a [crash](https://github.com/baskerville/plato/files/3199525/crash.log) saying: `thread 'main' panicked at 'no entry found for key'`.  If I remember correctly I was browsing it, which is slow, it went unresponsive and I tried to get back to the shelf by touching the center of the screen. After a few second it rebooted.
I wasn't able to reproduce it.

**Comment by baskerville** [comment]
Please use the attached release binary (with debug symbols). And in `plato.sh`, replace:
```sh
./plato >> info.log 2>&1 || mv info.log crash.log
```
with:
```sh
RUST_BACKTRACE=1 ./plato >> info.log 2>&1 || mv info.log crash.log
```

If you manage to reproduce or encounter another crash, `crash.log` will provide a useful backtrace.

[plato-0.7.1-release_debug_binary.zip](https://github.com/baskerville/plato/files/3206578/plato-0.7.1-release_debug_binary.zip)

**Comment by baskerville** [comment]
I was able to reproduce this somehow. I've got additional messages:
```
error: malloc of 2482272 bytes failed
error: malloc of 5911576 bytes failed
```

I will try to investigate.

**Comment by baskerville** [comment]
This is quite easy to reproduce:

1. Open a large PDF.
2. Jump to a random page.
3. Go to step 2.

Running `free -m` on each page jump shows the associated drop in the amount of free memory.

The problem is specific to *MuPDF*. I'm assuming that it has to do with *MuPDF*'s cache. But the cache shouldn't grow beyond [32 MiB](https://github.com/baskerville/plato/blob/5264af1d568d20de1933c7663d935369167084dd/src/document/mupdf_sys.rs#L18)…

**Comment by baskerville** [comment]
This is a [bug](https://bugs.ghostscript.com/show_bug.cgi?id=701476) in *MuPDF*.
