### ISSUE TITLE
Position off by a few pages after changing font size

### ISSUE THREAD

**Issue by taosxx** [baskerville/plato#7]
Affected: Plato 0.3.0
How to reproduce:
* open a document in Plato (in my case it was an epub)
* go to the beginning of a chapter (not necessary but easier to see)
* open the top menu
* increase the font size with the slider -> position in the book is now off by a few pages
or:
* decrease the font size with the slider -> position in the book is now also off by a few pages

**Comment by baskerville** [comment]
First a warning: I found a problem that makes *Plato* consume 99 % of the CPU resources in idle state. This problem was fixed in version *0.3.2*. Please don't use any version below that.

Now, regarding this issue: I noticed this behavior.

The method currently used to recompute the current page doesn't use the text layer: it only considers the current page and the total number of pages.

There's another problem that might contribute to the drift: sometimes, [mupdf returns an incorrect value for the pages count!](https://bugs.ghostscript.com/show_bug.cgi?id=698770)

**Comment by baskerville** [comment]
This is fixed by the built-in ePUB renderer.
