### ISSUE TITLE
[question] Issues adding dictionnaries

### ISSUE THREAD

**Issue by Aang23** [baskerville/plato#84]
How should I go about adding a dictionary?
I converted StarDict's Gcide to dictd, and tried putting it in the "dictionaries" folder pretty much everywhere. Neither .adds/plato or /mnt/onboard seems to work.

What can I be possibly doing wrong?

Thanks for this awesome reader btw!

**Comment by baskerville** [comment]
The `dictionaries` directory simply needs to live alongside the `plato` binary. So if the `plato` binary is in `.adds/plato`, you need to create the directory there. If you add dictionaries while the *Dictionary* application is running, tap the *Dictionary* label and select *Reload Dictionaries*. Also please note that each *dictd* dictionary is made of two files: one ending with `.index` and the other with `.dict.dz` (or `.dict`).

**Comment by Aang23** [comment]
Thanks! Got it to work.
I had forgotten to transfer the .index file as well.

**Comment by definev** [comment]
I have .dict and .idx file i copy this to dictionaries folder, plato can't recognized that

**Comment by baskerville** [comment]
> I have .dict and .idx file i copy this to dictionaries folder, plato can't recognized that

You can convert *StarDict* dictionaries using [sdunpack](https://github.com/baskerville/sdunpack#convert-stardict-to-dictd).

**Comment by definev** [comment]
![image](https://user-images.githubusercontent.com/62325868/92323631-721b2980-f064-11ea-9052-b25c4aa87523.png)
I have this issue

**Comment by baskerville** [comment]
> https://user-images.githubusercontent.com/62325868/92323631-721b2980-f064-11ea-9052-b25c4aa87523.png

I've added a binary for windows: https://github.com/baskerville/sdunpack/releases/tag/0.2.0

**Comment by LiquidN2** [comment]
Hi,

Sorry for reopening this issue but I'm having trouble converting StarDict to dictd in order to add dictionaries to Plato.  I'm not super technical so please bear with me.

I'm using a Windows 10 computer and I've downloaded your binary file.  In your instruction, you run `dictzip` to uncompress the `*.dz` file first.  I'm guessing this is to get the `*.dict` file for `sdunpack` to work on?  But `dictzip` and `dictfmt` aren't commands on Windows 10.  Please help.

I'm loving Plato so far.  Using the latest version 0.9.16.  It is quite fast compared to Nickel.

Thanks!

**Comment by baskerville** [comment]
> In your instruction, you run `dictzip` to uncompress the `*.dz` file first. I'm guessing this is to get the `*.dict` file for `sdunpack` to work on?

Correct.

> But `dictzip` and `dictfmt` aren't commands on Windows 10.

I forgot to mention this in the README: `dictzip` and `dictfmt` are provided by [dictd](https://sourceforge.net/projects/dict/files/dictd/). Unfortunately, there doesn't seem to be any [MSYS2](https://www.msys2.org/) package for this: you'd have to build it from source.

**Comment by LiquidN2** [comment]
> I forgot to mention this in the README: `dictzip` and `dictfmt` are provided by [dictd](https://sourceforge.net/projects/dict/files/dictd/). Unfortunately, there doesn't seem to be any [MSYS2](https://www.msys2.org/) package for this: you'd have to build it from source.

Unfortunately this might be a bit too technical for me since I'm not an e-reader developer.  I have a Mac which I don't think solve the problem since these files aren't executables on MacOS.  I'm not familiar with these packages and how they work. 😥

Perhaps in the future releases of Plato, would you consider including a dictionary like [this one](http://download.huzheng.org/bigdict/stardict-Merriam-Webster_s_Collegiate_11th_Ed-2.4.2.tar.bz2)?  Or if you're not able to do that because of copyright issue, would you be able to help me convert it?  If not, that's ok too.  I appreciate that you're trying to help anyways 😁

Cheers!

**Comment by baskerville** [comment]
> I have a Mac which I don't think solve the problem since these files aren't executables on MacOS.

There's a binary for *macOS*. If you install [*Homebrew*](https://brew.sh/), it'll also be easier to install *dictd*: `brew install dict`.

> Or if you're not able to do that because of copyright issue, would you be able to help me convert it?

What I could do is add a feature in *Plato* for converting *StarDict* dictionaries.

**Comment by baskerville** [comment]
As of 0.9.17, you can just unpack *StarDict* dictionaries, in the `dictionaries` directory. They will be converted automatically during startup.

**Comment by foldfree** [comment]
Thank you so much for implementing this.
I want to confirm it works. Although it's not difficult to do, documentation and process is not on the wiki so I would like to describe my process for eventual noobs out there.

1. Download _StarDict_ dictionaries from your favorite place, I recommend [wikitionary dumps](https://github.com/BoboTiG/ebook-reader-dict).
2. Extract the archives, each in a subfolder located at .adds/plato/dictionaries/. 
3. Restart Plato. It will take a few minutes for the conversion to happen.
4. Plato is launched, dictionaries are ready to use in the 'application' submenu or 'define' action when selecting a word.

**Comment by anarcat** [comment]
i just struggled with this and found that last comment to be tremendously useful. it would fit well in the GUIDE.md IMHO. :)
