### ISSUE TITLE
[question] What is the use case for hooks?

### ISSUE THREAD

**Issue by rien333** [baskerville/plato#85]
Bit of a silly question maybe, but I can't figure out what the hook system is all about (and my hooks keep getting removed from `Setting.toml`, but that's maybe because I'm not defining them right. Are you sure the syntax in the example in `docs/HOOKS.md` is right?). 

First, what is the purpose of hooks? In a program like emacs, a hook would react to a certain event. Is it the same for plato? To what sort of events do hooks respond? For example, could I tell plato to do something when a  wifi  connection is established? 

Second, I'm not totally sure how to even begin testing hooks. Say, I have a random test program on my Kobo, `/opt/foo`. How would I use plato's hook system to run it (just as a test case)? 

Finally, with the term "categories"  in `doc/HOOKS.md` you mean the row of user defined categories on the home screen, right? 

**EDIT:** Running on the latest commit (https://github.com/baskerville/plato/commit/367cceb30c3dac224cf205b3d602014e5a94622e), btw.

**Comment by baskerville** [comment]
> Bit of a silly question maybe, but I can't figure out what the hook system is all about

The hook system provides a way to fetch external contents in real time. An example program using the hook system is the [Wallabag article fetcher](https://github.com/baskerville/plato/blob/master/src/fetcher.rs).

> (and my hooks keep getting removed from `Setting.toml`, but that's maybe because I'm not defining them right.

[Just remove the `hooks = []` line.](https://www.mobileread.com/forums/showpost.php?p=3932818&postcount=487) 

The problem is fixed in 367cceb for future users.

> Are you sure the syntax in the example in `docs/HOOKS.md` is right?).

Yes.

> First, what is the purpose of hooks? In a program like emacs, a hook would react to a certain event. Is it the same for plato? To what sort of events do hooks respond?

Hooks are triggered by selecting categories. When the program associated with a hook is running, it can communicate with *Plato* by writing JSON messages on its standard output.

> For example, could I tell plato to do something when a wifi connection is established?

You can set the WiFi state from a program. Your program will receive a `SIGUSR1` signal when the connection is established (as mentioned in the documentation).

> Second, I'm not totally sure how to even begin testing hooks. Say, I have a random test program on my Kobo, `/opt/foo`. How would I use plato's hook system to run it (just as a test case)?

Just append the following to your `Settings.toml`:
```
[[home.hooks]]
name = "Test"
program = "/opt/foo"
```

And *foo* might be:
```sh
#! /bin/sh

echo '{"type": "notify", "message": "Hello World!"}'
```

Then tap the lower left books/matches count label (of the *Home* view), tap `Toggle Hook` and then `Test`.

> Finally, with the term "categories" in `doc/HOOKS.md` you mean the row of user defined categories on the home screen, right?

Yes I do. If you're uncertain about what a [category](https://github.com/baskerville/plato/blob/master/doc/CATEGORIES.md) is, I might have some work to do on the documentation!

**Comment by rien333** [comment]
Cool, thanks for the extensive explanation. 

> Yes I do. If you're uncertain about what a category is, I might have some work to do on the documentation!

No the documentation is fine if you, as the reader, put in some effort (which I might have failed at). I just was missing the bigger picture, that's all.

**Comment by rien333** [comment]
@baskerville  I think I have figured out my problem. Although other files persist after a reboot (e.g. I can use `vi` over ssh and edit random text files), `Settings.toml` always returns to it's previous state after a reboot. Any idea how to debug/what might be wrong? Btw, I generally edit `Settings.toml` over ssh, instead of USB, as my computers USB3 port is currently kinda of broken (don't think this matters, but just to be sure). 

For reference, here is my current `Settings.toml` file. It includes the hook-related snippet you provided at the bottom, but that keeps disappearing after rebooting - as do other things I change in the file:

https://0x0.st/z5Ky.toml

**Comment by baskerville** [comment]
> `Settings.toml` always returns to it's previous state after a reboot. Any idea how to debug/what might be wrong?

You can edit `Settings.toml` if:
- *Plato* isn't running.
- *Plato* is running in *shared* mode.
